---
#
# Ansible playbook to set up webservers
#

- hosts: webservers
  remote_user: centos
  roles:
    - { role: webpackages }
    - { role: websettings }
    - { role: webcontent }
  become: true
  handlers:
    - name: restart apache
      service: 
        name: httpd 
        state: restarted
      become: true
 
- hosts: loadbalancers
  remote_user: centos
  roles:
    - { role: webpackages }
    - { role: lbsettings }
  become: true
  handlers:
    - name: restart apache
      service: 
        name: httpd
        state: restarted
      become: true
